---
- name: Remove relay db
  file:
    path: /home/{{ USERNAME_AND_FILENAME_PREFIX }}-{{ item }}/.local/share/robonomics/polkadot/chains/{{ chain_id }}/db
    state: absent 
  loop: "{{ target_collators_index }}"
  tags: [ never, remove_relaychain_db, remove_dbs ]

- name: Remove parachain db
  file:
    path: /home/{{ USERNAME_AND_FILENAME_PREFIX }}-{{ item }}/.local/share/robonomics/chains/{{ parachain_name }}/db
    state: absent
  loop: "{{ target_collators_index }}" 
  tags: [ never, remove_parachain_db, remove_dbs ]