---
- import_tasks: set_facts.yml
- import_tasks: ufw.yml

- name: STOP ALL EXISTING ROBONOMICS SERVICES
  block:
    - name: "Stop all robonomics services"
      # shell: if systemctl is-enabled --quiet {{ item }}; then systemctl restart {{ item }} && echo restarted ; fi
      service: name="{{ item }}.service" state=stopped
      loop: "{{ existing_collators_users.stdout_lines }}"
  rescue: 
    - name: Looks like user exists but service doesn't
      debug: msg="beep beep just go ahead"
  tags: [ always ]

- import_tasks: users.yml
- import_tasks: cron.yml
- import_tasks: binary.yml
- import_tasks: service.yml
- import_tasks: dbs.yml

- name: Start robonomics service
  service:
    name: "{{ USERNAME_AND_FILENAME_PREFIX }}-{{ item }}.service"
    state: restarted
    enabled: yes
  loop: "{{ target_collators_index }}"
  tags: [ start, restart, ufw ]
