---
## Use inventory var 'host-collators-count' if it's defined, else use it from defaults
- name: "Set host collators count"
  set_fact:
    host_collators_count: "{{ hostvars[inventory_hostname]['host-collators-count'] | int }}"
  when: hostvars[inventory_hostname]['host-collators-count'] is defined
  tags: [ always ]

- debug: msg={{ host_collators_count }}
  tags: [ debug ]

- name: "Generate collators index"
  set_fact: collators_index={{ range(1, host_collators_count|int + 1) | list }}
  tags: [always]
    
- debug: msg={{ collators_index }}
  tags: [ debug ]


- name: "Stop all robonomics services"
  service:
    name: "{{ USERNAME_AND_FILENAME_PREFIX }}-{{ item }}.service"
    state: stopped
  loop: "{{ collators_index }}"
  tags: [ always ]


## Users Management
- name: "Generate target collators users list"
  set_fact: target_collators_users={{ target_collators_users | default([]) + ['-'.join((USERNAME_AND_FILENAME_PREFIX, item|string))] }}
  loop: "{{ collators_index | list }}"
  tags: [ always ]

- debug: msg={{ target_collators_users }}
  tags: [ debug ]


- name: "Determine existing collators users list"
  shell: 'grep "{{ USERNAME_AND_FILENAME_PREFIX }}" /etc/group | cut -d: -f1 | tr \",\" \"\\n\"'
  changed_when: false 
  register: existing_collators_users
  tags: [ always ]

- debug: msg={{ existing_collators_users }}
  tags: [ debug ]


- name: "Generate unecessary users list"
  set_fact: unecessary_users={{ existing_collators_users.stdout_lines | difference(target_collators_users) }}
  tags: [ always ]

- name: "Unecessary users"
  debug: msg="{{ unecessary_users }}"
  tags: [ debug ]

- name: "Remove unnecessary users"
  ansible.builtin.user:
    name: "{{ item }}"
    state: absent
    remove: yes
  loop: "{{ unecessary_users }}"

- name: "Remove all collators users"
  ansible.builtin.user:
    name: "{{ USERNAME_AND_FILENAME_PREFIX }}-{{ item }}"
    state: absent
    remove: yes
  loop: "{{ collators_index }}"
  tags: [ never, remove ]
### /Users management

# - name: "Delete unecessary services"
#   file:
#     path: /etc/systemd/system/{{ USERNAME_AND_FILENAME_PREFIX }}-{{ item }}.service
#     state: absent
#   loop: 



- name: "Create collators users"
  user:
    name: "{{ USERNAME_AND_FILENAME_PREFIX }}-{{ item }}"
    state: present
  loop: "{{ collators_index }}"


- name: Download Robonomics archive
  get_url: url=https://github.com/airalab/robonomics/releases/download/v{{ robonomics_version }}/robonomics-{{ robonomics_version }}-x86_64-unknown-linux-gnu.tar.gz dest=/root/

- name: Unpack Robonomics binary to /usr/bin/robonomics
  ansible.builtin.unarchive: src=/root/robonomics-{{ robonomics_version }}-x86_64-unknown-linux-gnu.tar.gz dest=/usr/bin/ remote_src=yes

- name: Template robonomics.service
  template:
    src: robonomics-collator.service.j2
    dest: /etc/systemd/system/{{ USERNAME_AND_FILENAME_PREFIX }}-{{ item }}.service
  loop: "{{ collators_index }}"

- name: "Reload systemd"
  shell: systemctl daemon-reload
  tags: [ always ]

- name: Remove relay db
  file:
    path: /home/{{ USERNAME_AND_FILENAME_PREFIX }}-{{ item }}/.local/share/robonomics/polkadot/chains/{{ chain_id }}/db
    state: absent 
  loop: "{{ collators_index }}"
  tags: [ never, remove_relaychain_db, remove_dbs ]

- name: Remove parachain db
  file:
    path: /home/{{ USERNAME_AND_FILENAME_PREFIX }}-{{ item }}/.local/share/robonomics/chains/earth/db
    state: absent
  loop: "{{ collators_index }}" 
  tags: [ never, remove_parachain_db, remove_dbs ]

- name: Start robonomics service
  service:
    name: "{{ USERNAME_AND_FILENAME_PREFIX }}-{{ item }}.service"
    state: restarted
    enabled: yes
  loop: "{{ collators_index }}"
