---
- name: Template robonomics.service
  template:
    src: robonomics-collator.service.j2
    dest: /etc/systemd/system/{{ USERNAME_AND_FILENAME_PREFIX }}-{{ item }}.service
  loop: "{{ target_collators_index }}"
  notify:
    - daemon-reload